links:
  rails_tutorial:
    author: https://www.michaelhartl.com/
    home_page: https://www.railstutorial.org/
    help_page: https://www.railstutorial.org/help
    book_page: https://www.railstutorial.org/book
    contact_page: https://www.railstutorial.org/contact
    screencasts_page: https://screencasts.railstutorial.org/
  learn_enough: https://www.learnenough.com/
  gravartar: https://secure.gravatar.com/avatar/
  gravartar_change: https://gravatar.com/emails

validations:
  name:
    max_length: 50
  email:
    max_length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  password:
    min_length: 6

gravartar:
  size_default: 80
  size_list: 50
