links:
  rails_tutorial:
    author: https://www.michaelhartl.com/
    home_page: https://www.railstutorial.org/
    help_page: https://www.railstutorial.org/help
    book_page: https://www.railstutorial.org/book
    contact_page: https://www.railstutorial.org/contact
    screencasts_page: https://screencasts.railstutorial.org/
  learn_enough: https://www.learnenough.com/
